_dataset:
  type: KITTIColorDepthDataset
  params:
    split_file: data_splits/kitti/train_list.txt
    full_size: [384, 1280]
    patch_size: [192, 640]
    random_resize: True
    normalize_params: [0.411, 0.432, 0.45]
    flip_mode: k
    color_aug: True
    output_frame: ['o']
    multi_out_scale: null
    load_KTmatrix: True
    load_depth: True
    load_depthhints: False
    is_fixK: True
    stereo_test: False
    jpg_test: False
    improved_test: False
