_dataset:
  params:
    split_file: data_splits/kitti/train_list.txt
    full_size: [192, 640]
    is_KTmatrix: True
    is_fixK: True
    normalize_params: [0, 0, 0]
    flip_mode: k
    multi_out_scale: [3,2,1]

_base: options/_base/datasets/kitti/_base.yaml