_dataset:
  params:
    split_file: data_splits/kitti/train_list.txt
    full_size: [384, 1280]
    patch_size: [192, 640]
    is_fixK: True
    flip_mode: k

_base: options/_base/datasets/kitti/_base.yaml
