train_dataset:
  params:
    is_fixK: v2
    multi_out_scale: null

model:
  params:
    decoder_mode: '3'
    image_size: [192, 640]

losses:
  param_group:
    _optim: options/_base/optimizers/adam09.yaml
    optim:
      type: AdamW
      lr: 0.0002
      params:
        weight_decay: 0.00005
      sched:
        type: Step
        params:
          milestones: [40]  
    loss_terms:
      photo_auto_min-0:
        type: MD2_PhotoLoss
        rate: 0.81
        name: photo_auto_min-0
        args:
          preds_n: ['proj_img_-1_0_{}',
                    'proj_img_1_0_{}']
          idents_n: [color_-1,
                    color_1]
          target_n: color_{}
      photo_auto_min-1:
        type: MD2_PhotoLoss
        rate: 0.9
        args:
          preds_n: ['proj_img_-1_1_{}',
                    'proj_img_1_1_{}']
          idents_n: [color_-1,
                    color_1]
          target_n: color_{}
      photo_auto_min-2:
        type: MD2_PhotoLoss
        rate: 1
        args:
          preds_n: ['proj_img_-1_2_{}',
                    'proj_img_1_2_{}']
          idents_n: [color_-1,
                    color_1]
          target_n: color_{}
      smooth-0:
        type: SmoothLoss
        rate: 0.00081
        args:
          pred_n: disp_0_{}
          image_n: color_{}
          relative_smo: True
      smooth-1:
        type: SmoothLoss
        rate: 0.0009
        args:
          pred_n: disp_1_{}
          image_n: color_{}
          relative_smo: True
      smooth-2:
        type: SmoothLoss
        rate: 0.001
        args:
          pred_n: disp_2_{}
          image_n: color_{}
          relative_smo: True

pred_size: [192, 640]


visual:
  type:
    color_s: img
    disp_0_s: disp
    photo_auto_min-0/s: error_heat
    proj_img_1_0_s: img
    proj_img_-1_0_s: img
    disp_2_s: disp
    disp_1_s: disp
  shape: [[color_s, photo_auto_min-0/s],
          [proj_img_1_0_s, proj_img_-1_0_s],
          [disp_0_s, disp_1_s],
          [disp_2_s, disp_2_s]]

_train: options/_base/datasets/kitti/train_192_mono.yaml
_val: options/_base/datasets/kitti/test_192.yaml
_base: options/_base/networks/r-msfm.yaml
