train_dataset:
  params:
    full_size: null
    flip_mode: img

val_dataset:
  params:
    full_size: null

model:
  params:
    mom_module: True

losses:
  param_group1:
    loss_terms: {}
  param_group2:
    optim:
        lr: 0.00005
    loss_terms:
      photo_l1:
        type: PhotoLoss
        rate: 1
        args:
          pred_n: synth_img_{}
          target_n: color_{}_aug
          l1_rate: 1
          other_side: True
      perceptual-1:
        type: PhotoLoss
        rate: 0.01
        args:
          pred_n: synth_feats_0_{}
          target_n: raw_feats_0_{}
          l1_rate: 0
          l2_rate: 1
      perceptual-2:
        type: PhotoLoss
        rate: 0.01
        args:
          pred_n: synth_feats_1_{}
          target_n: raw_feats_1_{}
          l1_rate: 0
          l2_rate: 1
      perceptual-3:
        type: PhotoLoss
        rate: 0.01
        args:
          pred_n: synth_feats_2_{}
          target_n: raw_feats_2_{}
          l1_rate: 0
          l2_rate: 1
      smooth:
        type: SmoothLoss
        rate: 0.0016
        args:
          pred_n: disp_{}
          image_n: color_{}
          gamma_rate: 2
          more_kernel: True
          gray_img: True
      depth-ff:
        type: PhotoLoss
        rate: 1
        mask: ff_mask_{}
        args:
          pred_n: depth_{}
          target_n: depth_ff_{}
          l1_rate: 1

visual:
  type:
    color_s: img
    disp_s: disp
    disp_f_s: disp
    synth_img_s: img
    mask_s: mask
    depth-ff/s: error_heat
    color_o: img
    disp_o: disp
    disp_f_o: disp
    synth_img_o: img
    mask_o: mask
    depth-ff/o: error_heat
  shape: [[color_s, color_o],
          [disp_s, disp_o],
          [disp_f_s, disp_f_o],
          [synth_img_o, synth_img_s],
          [mask_s, mask_o],
          [depth-ff/s, depth-ff/o]]

_train: options/_base/datasets/kitti/train_384rc.yaml
_val: options/_base/datasets/kitti/test_384.yaml
_base: options/_base/networks/fal_net.yaml
